In [1]:
import pymysql

conn = pymysql.connect(
    host="localhost",
    user="root",
    password="Pashanlake@1",
    port=3306
)
print("Connected!")
conn.close()

Connected!

In [3]:
import sys
print(sys.executable)

C:\Users\win\anaconda3\python.exe

In [7]:
!"C:\Users\win\anaconda3\python.exe" -m pip install pymysql

Requirement already satisfied: pymysql in c:\users\win\anaconda3\lib\site-packages (1.2.0)

In [1]:
from sqlalchemy import create_engine, text
from urllib.parse import quote_plus

password = quote_plus("Pashanlake@1")
engine = create_engine(f"mysql+pymysql://root:{password}@localhost:3306/olist")

with engine.connect() as conn:
    print(conn.execute(text("SELECT DATABASE()")).scalar())

NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:mysql.pymysql

In [2]:
import sys
print("Python:", sys.executable)

import pymysql
print("pymysql version:", pymysql.__version__)

import sqlalchemy
print("SQLAlchemy version:", sqlalchemy.__version__)

Python: C:\Users\win\anaconda3\python.exe
pymysql version: 2.2.8
SQLAlchemy version: 1.4.39

In [3]:
!"C:\Users\win\anaconda3\python.exe" -m pip show pymysql

Name: PyMySQL
Version: 1.2.0
Summary: Pure Python MySQL Driver
Home-page:
Author:
Author-email: Inada Naoki <songofacandy@gmail.com>, Yutaka Matsubara <yutaka.matsubara@gmail.com>
License:
Location: C:\Users\win\anaconda3\Lib\site-packages
Requires:
Required-by:

In [4]:
import pymysql
print(pymysql.__file__)

C:\Users\win\anaconda3\Lib\site-packages\pymysql\__init__.py

In [5]:
!"C:\Users\win\anaconda3\python.exe" -m pip uninstall -y pymysql

Found existing installation: PyMySQL 1.2.0
Uninstalling PyMySQL-1.2.0:
  Successfully uninstalled PyMySQL-1.2.0

In [6]:
import shutil, os
path = r"C:\Users\win\anaconda3\Lib\site-packages\pymysql"
if os.path.exists(path):
    shutil.rmtree(path)
    print("Removed leftover folder")
else:
    print("Already clean")

Already clean

In [7]:
!"C:\Users\win\anaconda3\python.exe" -m pip install pymysql

Collecting pymysql
  Obtaining dependency information for pymysql from https://files.pythonhosted.org/packages/a9/4b/0a906d8184f011ff8dbd4722743783867589b33269d2c5fff238d636fdcb/pymysql-1.2.3-py3-none-any.whl.metadata
  Downloading pymysql-1.2.3-py3-none-any.whl.metadata (4.2 kB)
Downloading pymysql-1.2.3-py3-none-any.whl (46 kB)
   ---------------------------------------- 0.0/46.7 kB ? eta -:--:--
   ---------------------------------------- 46.7/46.7 kB 2.4 MB/s eta 0:00:00
Installing collected packages: pymysql
Successfully installed pymysql-1.2.3

In [1]:
import pymysql
print(pymysql.__version__)
print(pymysql.__file__)

2.2.8
C:\Users\win\anaconda3\Lib\site-packages\pymysql\__init__.py

In [3]:
from sqlalchemy import create_engine, text
from urllib.parse import quote_plus

password = quote_plus("Pashanlake@1")
engine = create_engine(f"mysql+pymysql://root:{password}@localhost:3306/olist")

with engine.connect() as conn:
    print(conn.execute(text("SELECT DATABASE()")).scalar())

NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:mysql.pymysql

In [4]:
with open(r"C:\Users\win\anaconda3\Lib\site-packages\pymysql\__init__.py", encoding="utf-8") as f:
    content = f.read()
print(content[:2000])

"""
PyMySQL: A pure-Python MySQL client library.

Copyright (c) 2010-2016 PyMySQL contributors

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
"""

import sys

from .constants import FIELD_TYPE
from .err import (
    DatabaseError,
    DataError,
    Error,
    IntegrityError,
    InterfaceError,
    InternalError,
    MySQLError,
    NotSupportedError,
    OperationalError,
    ProgrammingError,
    Warning,
)
from .times import (
    Date,
    DateFromTicks,
    Time,
    TimeFromTicks,
    Timestamp,
    TimestampFromTicks,
)

# PyMySQL version.
# Used by setuptools and connection_attrs
VERSION = (1, 2, 3, "final")
VERSION_STRING = "1.2.3"

### for mysqlclient compatibility
### Django checks mysqlclient version.
version_info = (2, 2, 8, "final", 1)
__version__ = "2.2.8"


def get_client_info():  # for MySQLdb compatibility
    return __version__


def install_as_MySQLdb():
    """
    After this function is called, any application that imports MySQLdb
    will unwittingly actually use pymysql.
    """

In [5]:
import sqlalchemy, os
print(sqlalchemy.__file__)

dialect_path = os.path.join(os.path.dirname(sqlalchemy.__file__), "dialects", "mysql", "pymysql.py")
print("Dialect file exists:", os.path.exists(dialect_path))

C:\Users\win\anaconda3\Lib\site-packages\sqlalchemy\__init__.py
Dialect file exists: False

In [ ]:
!"C:\Users\win\anaconda3\python.exe" -m pip uninstall -y sqlalchemy
!"C:\Users\win\anaconda3\python.exe" -m pip install sqlalchemy

Found existing installation: SQLAlchemy 1.4.39
Uninstalling SQLAlchemy-1.4.39:
  Successfully uninstalled SQLAlchemy-1.4.39

In [1]:
import sqlalchemy
print(sqlalchemy.__version__)

2.0.54

In [2]:
import sqlalchemy, os
print(sqlalchemy.__file__)

dialect_path = os.path.join(os.path.dirname(sqlalchemy.__file__), "dialects", "mysql", "pymysql.py")
print("Dialect file exists:", os.path.exists(dialect_path))

C:\Users\win\anaconda3\Lib\site-packages\sqlalchemy\__init__.py
Dialect file exists: True

In [3]:
from sqlalchemy import create_engine, text
from urllib.parse import quote_plus

password = quote_plus("Pashanlake@1")
engine = create_engine(f"mysql+pymysql://root:{password}@localhost:3306/olist")

with engine.connect() as conn:
    print(conn.execute(text("SELECT DATABASE()")).scalar())

olist

In [10]:
import pandas as pd

df_orders = pd.read_sql("SELECT * FROM orders", engine)
df_orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,00010242fe8c5a6d1ba2dd792cb16214,3ce436f183e68e07877b285a838db11a,delivered,2017-09-13 08:59:02,2017-09-13 09:45:35,2017-09-19 18:34:16,2017-09-20 23:43:48,2017-09-29 00:00:00
1,00018f77f2f0320c557190d7a144bdd3,f6dd3ec061db4e3987629fe6b26e5cce,delivered,2017-04-26 10:53:06,2017-04-26 11:05:13,2017-05-04 14:35:00,2017-05-12 16:04:24,2017-05-15 00:00:00
2,000229ec398224ef6ca0657da4fc703e,6489ae5e4333f3693df5ad4372dab6d3,delivered,2018-01-14 14:33:31,2018-01-14 14:48:30,2018-01-16 12:36:48,2018-01-22 13:19:16,2018-02-05 00:00:00
3,00024acbcdf0a6daa1e931b038114c75,d4eb9395c8c0431ee92fce09860c5a06,delivered,2018-08-08 10:00:35,2018-08-08 10:10:18,2018-08-10 13:28:00,2018-08-14 13:32:39,2018-08-20 00:00:00
4,00042b26cf59d7ce69dfabb4e55b4fd9,58dbd0b2d70206bf40e62cd34e84d795,delivered,2017-02-04 13:57:51,2017-02-04 14:10:13,2017-02-16 09:46:09,2017-03-01 16:42:31,2017-03-17 00:00:00

In [11]:
df_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99441 non-null  object
 5   order_delivered_carrier_date   99441 non-null  object
 6   order_delivered_customer_date  99441 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

In [12]:
df_orders.describe()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
count,99441,99441,99441,99441,99441,99441,99441,99441
unique,99441,99441,8,98875,90734,81019,95665,459
top,fffe41c64501cc87c801fd61db3f6244,96d649da0cc4ff33bb408b199d4c7dcf,delivered,2018-04-11 10:48:14,,,,2017-12-20 00:00:00
freq,1,1,96478,3,160,1783,2965,522

In [13]:
df_customers=pd.read_sql("SELECT*FROM customers",engine)
df_customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,00012a2ce6f8dcda20d059ce98491703,248ffe10d632bebe4f7267f1f44844c9,6273,osasco,SP
1,000161a058600d5901f007fab4c27140,b0015e09bb4b6e47c52844fab5fb6638,35550,itapecerica,MG
2,0001fd6190edaaf884bcaf3d49edf079,94b11d37cd61cb2994a194d11f89682b,29830,nova venecia,ES
3,0002414f95344307404f0ace7a26f1d5,4893ad4ea28b2c5b3ddf4e82e79db9e6,39664,mendonca,MG
4,000379cdec625522490c315e70c7a9fb,0b83f73b19c2019e182fd552c048a22c,4841,sao paulo,SP

In [15]:


df_customers.info()
df_customers.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

       customer_zip_code_prefix
count              99441.000000
mean               35137.474583
std                29797.938996
min                 1003.000000
25%                11347.000000
50%                24416.000000
75%                58900.000000
max                99990.000000